In [23]:
# Initial imports
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [24]:
# Import loan_status.csv to Google Colab
from google.colab import files
uploaded = files.upload()

Saving applicants_data.csv to applicants_data (2).csv

In [40]:
# Read the CSV file into a Pandas DataFrame
df = pd.read_csv("applicants_data.csv")

# Review the DataFrame
df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [41]:
df.drop(columns=['EIN', 'NAME'], inplace=True)
df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [42]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [43]:
list(df.dtypes[df.dtypes == "object"].index)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [44]:
# Create a list of the columns with categorical variables
categorical_variables = ['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']
# Use the fit_transform method from the OneHotEncoder to encode the data
encoded_data = enc.fit_transform(df[categorical_variables])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [45]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Display sample data
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [47]:
# Create a DataFrame with the columnns containing numerical variables from the original dataset
numerical_variables_df = df.drop(columns = categorical_variables)

# Review the DataFrame
numerical_variables_df.head()

   STATUS  ASK_AMT  IS_SUCCESSFUL
0       1     5000              1
1       1   108590              1
2       1     5000              0
3       1     6692              1
4       1   142590              1

In [48]:
joined_df = pd.concat([numerical_variables_df, encoded_df], axis="columns", join="inner")
joined_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [49]:
# Define the target set y using the IS_SUCCESSFUL column
y = joined_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [50]:
# Define features set X by selecting all columns but Attrition_Yes and Attrition_No
X = joined_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [51]:
# Split the data into training and testing datasets
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [55]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [57]:
# Define the the number of inputs (features) to the model
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

number_input_features = len(X_train.iloc[0])
# Define the number of hidden nodes for the first hidden layer
# Use the mean of the number of input features plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer1 =  (number_input_features + 1) // 2

# Define the number of hidden nodes for the second hidden layer
# Use the mean of the number of hidden nodes in the first hidden layer plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer2 = (hidden_nodes_layer1 + 1) // 2

# Create the Sequential model instance
nn = Sequential()

# Add the first hidden layer specifying the number of inputs, the number of hidden nodes, and the activation function
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Add the second hidden layer specifying the number of hidden nodes and the activation function
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [58]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 58)                6786

 dense_1 (Dense)             (None, 29)                1711

 dense_2 (Dense)             (None, 1)                 30

=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

In [59]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [60]:
# Fit the model using 100 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
804/804 [==============================] - 3s 2ms/step - loss: 0.5751 - accuracy: 0.7217
Epoch 2/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5544 - accuracy: 0.7292
Epoch 3/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5517 - accuracy: 0.7299
Epoch 4/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5496 - accuracy: 0.7312
Epoch 5/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5469 - accuracy: 0.7318
Epoch 6/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5456 - accuracy: 0.7326
Epoch 7/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5452 - accuracy: 0.7339
Epoch 8/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5436 - accuracy: 0.7341
Epoch 9/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5431 - accuracy: 0.7343
Epoch 10/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5422 - accuracy: 0.7347
Epoch 11/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7357
Epoch 12/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5415 - accuracy: 0.7344
Epoch 13/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5403 - accuracy: 0.7358
Epoch 14/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5405 - accuracy: 0.7357
Epoch 15/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5400 - accuracy: 0.7375
Epoch 16/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5395 - accuracy: 0.7366
Epoch 17/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5388 - accuracy: 0.7381
Epoch 18/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5395 - accuracy: 0.7367
Epoch 19/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5390 - accuracy: 0.7366
Epoch 20/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5381 - accuracy: 0.7386
Epoch 21/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7380
Epoch 22/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5374 - accuracy: 0.7363
Epoch 23/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5376 - accuracy: 0.7375
Epoch 24/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5369 - accuracy: 0.7386
Epoch 25/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5367 - accuracy: 0.7373
Epoch 26/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5374 - accuracy: 0.7383
Epoch 27/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5369 - accuracy: 0.7381
Epoch 28/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5359 - accuracy: 0.7397
Epoch 29/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7392
Epoch 30/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5363 - accuracy: 0.7383
Epoch 31/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5357 - accuracy: 0.7381
Epoch 32/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5351 - accuracy: 0.7388
Epoch 33/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5354 - accuracy: 0.7393
Epoch 34/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5349 - accuracy: 0.7385
Epoch 35/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7395
Epoch 36/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5349 - accuracy: 0.7398
Epoch 37/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5341 - accuracy: 0.7387
Epoch 38/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5344 - accuracy: 0.7395
Epoch 39/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5339 - accuracy: 0.7403
Epoch 40/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5340 - accuracy: 0.7391
Epoch 41/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5339 - accuracy: 0.7406
Epoch 42/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5338 - accuracy: 0.7397
Epoch 43/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7391
Epoch 44/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5334 - accuracy: 0.7406
Epoch 45/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5329 - accuracy: 0.7388
Epoch 46/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5331 - accuracy: 0.7401
Epoch 47/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5332 - accuracy: 0.7404
Epoch 48/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5331 - accuracy: 0.7401
Epoch 49/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5326 - accuracy: 0.7408
Epoch 50/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5328 - accuracy: 0.7402
Epoch 51/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5331 - accuracy: 0.7405
Epoch 52/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5322 - accuracy: 0.7389
Epoch 53/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7410
Epoch 54/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5323 - accuracy: 0.7413
Epoch 55/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5320 - accuracy: 0.7400
Epoch 56/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5321 - accuracy: 0.7417
Epoch 57/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7403
Epoch 58/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5315 - accuracy: 0.7412
Epoch 59/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.7405
Epoch 60/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5314 - accuracy: 0.7411
Epoch 61/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5317 - accuracy: 0.7392
Epoch 62/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5313 - accuracy: 0.7414
Epoch 63/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5312 - accuracy: 0.7399
Epoch 64/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5312 - accuracy: 0.7412
Epoch 65/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5307 - accuracy: 0.7406
Epoch 66/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5311 - accuracy: 0.7414
Epoch 67/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5309 - accuracy: 0.7401
Epoch 68/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5310 - accuracy: 0.7413
Epoch 69/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5305 - accuracy: 0.7417
Epoch 70/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5303 - accuracy: 0.7405
Epoch 71/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7409
Epoch 72/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5302 - accuracy: 0.7409
Epoch 73/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5302 - accuracy: 0.7408
Epoch 74/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5302 - accuracy: 0.7408
Epoch 75/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5299 - accuracy: 0.7416
Epoch 76/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5306 - accuracy: 0.7418
Epoch 77/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5298 - accuracy: 0.7427
Epoch 78/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7417
Epoch 79/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7416
Epoch 80/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7407
Epoch 81/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5295 - accuracy: 0.7408
Epoch 82/100
804/804 [==============================] - 3s 4ms/step - loss: 0.5297 - accuracy: 0.7413
Epoch 83/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5297 - accuracy: 0.7422
Epoch 84/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5296 - accuracy: 0.7416
Epoch 85/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.7414
Epoch 86/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5297 - accuracy: 0.7426
Epoch 87/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5292 - accuracy: 0.7418
Epoch 88/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5292 - accuracy: 0.7417
Epoch 89/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5295 - accuracy: 0.7416
Epoch 90/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7421
Epoch 91/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5291 - accuracy: 0.7413
Epoch 92/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5292 - accuracy: 0.7429
Epoch 93/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5294 - accuracy: 0.7417
Epoch 94/100
804/804 [==============================] - 3s 3ms/step - loss: 0.5292 - accuracy: 0.7420
Epoch 95/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5289 - accuracy: 0.7423
Epoch 96/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7413
Epoch 97/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5288 - accuracy: 0.7421
Epoch 98/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5286 - accuracy: 0.7416
Epoch 99/100
804/804 [==============================] - 2s 2ms/step - loss: 0.5289 - accuracy: 0.7421
Epoch 100/100
804/804 [==============================] - 2s 3ms/step - loss: 0.5286 - accuracy: 0.7414

In [62]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.5576 - accuracy: 0.7292 - 359ms/epoch - 1ms/step
Loss: 0.5575640797615051, Accuracy: 0.7292128205299377

the accuracy is not good because the the number is not close to 1. the second attempt give us a better results.

In [65]:
# Set the model's file path
file_path = "Alphabetsoup.h5"

# Export your model to an HDF5 file
nn.save(file_path)