In [2]:
# Initial imports
import pandas as pd
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split

In [3]:
# Import loan_status.csv to Google Colab
from google.colab import files
uploaded = files.upload()

Saving applicants_data.csv to applicants_data.csv

In [4]:
# Read the CSV file into a Pandas DataFrame
df = pd.read_csv("applicants_data.csv")

# Review the DataFrame
df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [5]:
df.drop(columns=['EIN', 'NAME'], inplace=True)
df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [6]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [7]:
list(df.dtypes[df.dtypes == "object"].index)

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [8]:
# Create a list of the columns with categorical variables
categorical_variables = ['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']
# Use the fit_transform method from the OneHotEncoder to encode the data
encoded_data = enc.fit_transform(df[categorical_variables])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_encoders.py:868: FutureWarning: `sparse` was renamed to `sparse_output` in version 1.2 and will be removed in 1.4. `sparse_output` is ignored unless you leave `sparse` to its default value.
  warnings.warn(

In [9]:
# Create a DataFrame with the encoded variables
encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names_out(categorical_variables)
)

# Display sample data
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

In [10]:
# Create a DataFrame with the columnns containing numerical variables from the original dataset
numerical_variables_df = df.drop(columns = categorical_variables)

# Review the DataFrame
numerical_variables_df.head()

   STATUS  ASK_AMT  IS_SUCCESSFUL
0       1     5000              1
1       1   108590              1
2       1     5000              0
3       1     6692              1
4       1   142590              1

In [21]:
joined_df = pd.concat([numerical_variables_df, encoded_df], axis="columns", join="inner")
joined_df

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
34294,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34295,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34296,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34297,1,5000,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
34298,1,36500179,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0

In [22]:
# Define the target set y using the IS_SUCCESSFUL column
y = joined_df["SPECIAL_CONSIDERATIONS_Y"]

# Display a sample of y
y[:5]

0    0.0
1    0.0
2    0.0
3    0.0
4    0.0
Name: SPECIAL_CONSIDERATIONS_Y, dtype: float64

In [23]:
# Define features set X by selecting all columns but Attrition_Yes and Attrition_No
X = joined_df.drop(columns=['SPECIAL_CONSIDERATIONS_Y', 'SPECIAL_CONSIDERATIONS_N'])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,ORGANIZATION_Trust,INCOME_AMT_0,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [24]:
# Split the data into training and testing datasets
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [25]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

In [45]:
# Define the the number of inputs (features) to the model
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential

number_input_features = len(X_train.iloc[0])
# Define the number of hidden nodes for the first hidden layer
# Use the mean of the number of input features plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer1 = (number_input_features + 2)//3

# Define the number of hidden nodes for the second hidden layer
# Use the mean of the number of hidden nodes in the first hidden layer plus the number of output nurons
# Use the Python floor division (//) to return the quotent
hidden_nodes_layer2 = (hidden_nodes_layer1 + 2)//3

# Create the Sequential model instance
nn = Sequential()

# Add the first hidden layer specifying the number of inputs, the number of hidden nodes, and the activation function
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

# Add the second hidden layer specifying the number of hidden nodes and the activation function
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [46]:
# Display the Sequential model summary
nn.summary()

Model: "sequential_13"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_26 (Dense)            (None, 39)                4524

 dense_27 (Dense)            (None, 13)                520

 dense_28 (Dense)            (None, 1)                 14

=================================================================
Total params: 5,058
Trainable params: 5,058
Non-trainable params: 0
_________________________________________________________________

In [47]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [48]:
# Fit the model using 100 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
804/804 [==============================] - 4s 4ms/step - loss: 0.0476 - accuracy: 0.9893
Epoch 2/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0060 - accuracy: 0.9991
Epoch 3/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0058 - accuracy: 0.9991
Epoch 4/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0058 - accuracy: 0.9991
Epoch 5/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0057 - accuracy: 0.9991
Epoch 6/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0057 - accuracy: 0.9991
Epoch 7/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0057 - accuracy: 0.9991
Epoch 8/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0056 - accuracy: 0.9991
Epoch 9/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0056 - accuracy: 0.9991
Epoch 10/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0055 - accuracy: 0.9991
Epoch 11/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0056 - accuracy: 0.9991
Epoch 12/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0055 - accuracy: 0.9991
Epoch 13/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 14/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0056 - accuracy: 0.9991
Epoch 15/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0055 - accuracy: 0.9991
Epoch 16/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0054 - accuracy: 0.9992
Epoch 17/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 18/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 19/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 20/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 21/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 22/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0053 - accuracy: 0.9991
Epoch 23/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 24/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0056 - accuracy: 0.9991
Epoch 25/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 26/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 27/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 28/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 29/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 30/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 31/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 32/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 33/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 34/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 35/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 36/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 37/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 38/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 39/50
804/804 [==============================] - 4s 5ms/step - loss: 0.0053 - accuracy: 0.9991
Epoch 40/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0055 - accuracy: 0.9991
Epoch 41/50
804/804 [==============================] - 4s 4ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 42/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 43/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 44/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 45/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 46/50
804/804 [==============================] - 3s 3ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 47/50
804/804 [==============================] - 2s 2ms/step - loss: 0.0053 - accuracy: 0.9992
Epoch 48/50
804/804 [==============================] - 2s 3ms/step - loss: 0.0052 - accuracy: 0.9992
Epoch 49/50
804/804 [==============================] - 4s 4ms/step - loss: 0.0054 - accuracy: 0.9991
Epoch 50/50
804/804 [==============================] - 3s 4ms/step - loss: 0.0052 - accuracy: 0.9992

In [50]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 0s - loss: 0.0052 - accuracy: 0.9993 - 354ms/epoch - 1ms/step
Loss: 0.0052364282310009, Accuracy: 0.9993003010749817

In [51]:
# Set the model's file path
file_path = "Alphabetsoup.h5"

# Export your model to an HDF5 file
nn.save(file_path)

the accuracy after is very better than the first attempt because the accuracy is improve, so
close to 1.